### ISSUE TITLE
Composition operator confusion

### ISSUE THREAD

**Issue by FranklinChen** [MedeaMelana/HoleyMonoid#1]
I was confused momentarily when I tried to use HoleyMonoid with just

``` haskell
import Data.HoleyMonoid
```

until I realized that I had to also manually add

``` haskell
import Prelude hiding ((.))
import Control.Category ((.))
```

Perhaps it should be documented that `(.)` needs to be imported. I was thinking maybe it would even simply be best to use a new operator as an alias to avoid the name clash altogether. (The `map` name clash also seems unnecessary.)

**Comment by MedeaMelana** [comment]
Hi Franklin,

Thanks for your feedback! As far as I'm aware, the behaviour you describe is very common among Haskell libraries, and the preferred way to do it. To avoid clashes with common functions, such as `map`, it's customary to import a module in qualified fashion:

`import qualified Data.HoleyMonoid as HM`

Then you can write `HM.map` to distinguish it from the map from Prelude. The philosophy is that you should be able to name your functions whatever is appropriate in the module/library, without having to worry about other modules' names.

I hope this helps.
